#!/usr/bin/perl -p

# make sure we can just write $...$ for formulas.
s/\$/\@f\$/g;

# however, undo that change if the dollar sign was escaped with a backslash
s/\\\@f\$/\$/g;

# We don't let doxygen put everything into a namespace
# dealii. consequently, doxygen can't link references that contain an
# explicit dealii:: qualification. remove it and replace it by the
# global scope
#
# Now, as of doxygen 1.5, this still produces the wrong result, but
# that's not our fault. This is reported here:
#    http://bugzilla.gnome.org/show_bug.cgi?id=365053
s/dealii::/::/g;

# Replace all occurrences of something like step-xx by
#    @ref step_xx "step-xx"
# so that doxygen properly cross references them. Before we had
# this rule, we actually had to write this sequence out in our
# documentation. Unfortunately, as a consequence, there are vestiges
# of this style, so we can't substitute things that look like
# "step-xx".
#
# There is another exception: the scripts in doc/doxygen/tutorial
# produce files that have table of contents entries. We don't
# want these cross-linked to itself.
s/(?<!\")step-(\d+)(?!\")/\@ref step_\1 \"step-\1\"/gi if !m/\@page/;
