Major:

* Mumps may have a transitive link interface to Scotch. Fix this

* Get rid of the last bits of unguarded platform introspection

Some last bits and thoughts:

* A TECPLOT feature has to be written

* Provide a configuration template for cross compiling with CMake,

* document that we no longer need the two-lib installation of p4est

* adjust doc/development/testsuite.html

* update https://code.google.com/p/dealii/wiki/Windows

* same for the Mac part...
