# $Id$
# Common Makefile for all test directories

all:
	cd base ; $(MAKE)
	cd lac ; $(MAKE)
	cd deal.II ; $(MAKE)

clean:
	cd base ; $(MAKE) clean
	cd lac ; $(MAKE) clean
	cd deal.II ; $(MAKE) clean
