######################################################################
# Makefile.rules,v 1.11 2001/04/24 13:18:09 wolf Exp
#
# Copyright (C) 2001, 2002, 2003, 2004, 2005, the deal.II authors
#
# Common make rules for test files. To be included by the Makefiles
# in the subdirectories.
######################################################################


normalize = $D/common/scripts/normalize.pl

WORKDIR = $(notdir $(shell pwd))

verbose = off


PLATFORM = $(TARGET)+$(GXX-VERSION:intel_%=%)
PLATFORM-HIERARCHY = $(shell $(PERL) ../hierarchy.pl $(PLATFORM))

############################################################
# First how to create executables, including all necessary
# flags:
############################################################

flags     = $(CXXFLAGS.g)

ifeq ($(findstring gcc,$(GXX_VERSION)),gcc)
flags += -Wno-missing-noreturn
endif

%/obj.g.$(OBJEXT) : %.cc Makefile
	@echo =====debug========= $<
	@$(CXX) $(flags) -c $< -o $@

%/obj.$(OBJEXT) : %.cc Makefile
	@echo =====optimized===== $<
	@$(CXX) $(CXXFLAGS.o) -c $< -o $@

######################################################################
# Don't put $(libraries) into this line since it is already in $^
######################################################################
%/exe :
	@echo =====linking======= $@
	@$(CXX) $(LDFLAGS) -o $@ ../abort.o $^ $(LIBS)


############################################################
# Next how to create output: by simply running a program.
# Note that we normalize output to a few digits after
# the decimal punct, in order to be able to check across
# different platforms where we might differ in round-off etc.
#
# Since the test suite is usually run automatically, we
# impose a maximum run time of 30 CPU minutes for each
# program.
#
# In the line after we execute the program, we make sure that
# the program terminated without error code; otherwise delete
# the output file and stop the make command. This is done so
# that when you run make for that output file again later
# then make would not say that the output file is up to
# date and does not need to be regenerated
############################################################

%/output : %/exe
	@echo =====Running======= $<
	@ulimit -t 2400 ; ./$< ; \
	  if test ! $$? = 0 ; then rm $@ ; false ; fi
	@perl -pi $(normalize)  $@



############################################################
# Postprocessing the output: compare with precomputed
# files. In default mode, do not show diffs as they are 
# usually overly verbose. Only if user calls `make' with
# flag `verbose=on' show the diffs. Also note that we
# usually let the call to `make' continue even if we
# find a difference, since the output is clearly marked
# as a failing test and we normally want to see the results
# of all tests at once, including those that come after
# the failed one.
#
# if, however, the flag `stop_on_error=on' was given, the
# check command fails whenever teh output differs from the
# precomputed file.
#
# as to finding which output file to compare with: we simply
# walk the list of files created by the ./hierarchy.pl file
# and take the first one.
############################################################


%/OK : %/output
	@echo '=====Checking======' $<
	@$(PERL) -pi $(normalize)  $<
	@for i in $(PLATFORM-HIERARCHY) ; do \
	    testname=$(<:%/output=%) ; \
	    if test -f $$testname/cmp/$$i ; then \
		cmpfile_found=yes ; \
		if test "x$(verbose)" = "xon" ; then \
			cmd="diff -w $< $$testname/cmp/$$i" ; \
		 else \
			cmd="diff -w $< $$testname/cmp/$$i > /dev/null" ; \
		 fi ; \
		 if eval $$cmd ; then \
			echo '=====OK============' $@ ; \
			touch $@ ; \
		 else \
			if test "x$(verbose)" = "xon" ; then \
				echo '+++++Error+++++++++' $@ ; \
			else \
				echo '+++++Error+++++++++ $@. Use make verbose=on for the diffs' ; \
			fi ; \
			if test "x$(stop_on_error)" = "xon" ; then \
				false ; \
			fi ; \
		 fi ; \
		 break ; \
	    fi ; \
	  done && \
	  if test "x$$cmpfile_found" != "xyes" ; then \
		echo "*** No suitable file in $$testname/cmp found! ***" ; \
		false ; \
	  fi


############################################################
# Generate a report for the present date, in which the
# results (indicated by a "+" for a successful test, and a
# "-" for a failing one) for all tests is summarized. Use
# universal time in order to be able to run this target
# anywhere anytime
############################################################
report:
	@for test in $(sort $(tests)) ; do \
		if (($(MAKE) $$test/OK stop_on_error=on 2>&1) > /dev/null); then \
			echo `date -u +"%Y-%m-%d %H:%M"` + $(WORKDIR)/$$test ; \
		else \
			echo `date -u +"%Y-%m-%d %H:%M"` - $(WORKDIR)/$$test ; \
		fi ; \
	done


report+mail:
	@$(MAKE) report | tee testresults
	@cat testresults | mail regression-tests@dealii.org
	@rm testresults


############################################################
# Generating references: Useful when creating references for
# a new platform or when updating several non-generic
# references.
############################################################
%/ref : %/output
	@$(PERL) -pi $(normalize)  $<
	@for i in $(PLATFORM-HIERARCHY) ; do \
	    testname=$(<:%/output=%) ; \
	    if test -f $$testname/cmp/$$i ; then \
	        cmd="diff -w $< $$testname/cmp/$$i > /dev/null" ; \
		if eval ! $$cmd ; then \
		    echo '=====Creating======' $$testname/cmp/$(PLATFORM) ; \
		    cp $$testname/output $$testname/cmp/$(PLATFORM); \
		fi ; \
		break ; \
	    fi ; \
	  done


############################################################
# After all these general rules, here is the target to be
# executed by make: for each entry in the list $(tests)
# perform a check.
############################################################
run-tests: $(tests:%=%/OK)

output: $(tests:%=%/output)

build: $(tests:%=%/exe)

refs: $(tests:%=%/ref)

############################################################
# Link and copy files in ./results/* to generate checked
# checked files for new hardware/compiler platform.
#
# It is expected that the tests are run with ./compare being
# sym-linked to a suitable existing result directory.
#
# The current subdirectory must exist there.
############################################################
new-platform: output run-tests
	csh ../newplatform.csh $(WORKDIR) $(TARGET)+$(GXX-VERSION)

############################################################
# Cleanup targets
############################################################

clean:
	-rm -f Makefile.depend Makefile.tests */obj.$(OBJEXT) \
               */obj.g.$(OBJEXT) */output *~

distclean: clean
	-rm -f */exe *.testcase *.inp *.gpl *.eps *.gnuplot


show-tests:
	@echo $(tests)

############################################################
# Automatic generation of dependencies
############################################################

Makefile.depend: $(shell echo *.cc)
	@echo =====Dependencies== $@
	@$D/common/scripts/make_dependencies $(INCLUDE) $^ > $@ \
		|| (rm -f $@ ; false)
	@$(PERL) -pi -e 's#\.((g\.)?$(OBJEXT):)#/obj.\1#g;' $@

Makefile.tests: $(shell echo *.cc)
	@echo =====Targets======= $@
	@for i in $(tests) ; do \
		echo "$$i/exe : $$i/obj.g.\$$(OBJEXT) \$$(libraries)"; \
	 done \
		> $@


.PHONY: report show-tests clean distclean %/ref

subdirs:
	for i in $(tests) ; do \
	  mkdir $$i/cmp ; \
	  cp ../results/i686-pc-linux-gnu+gcc3.2/bits/$$i.output $$i/cmp/generic ; \
	  cp ../results/i686-pc-linux-gnu+gcc3.4/bits/$$i.output $$i/cmp/i686-pc-linux-gnu+gcc3.4 ; \
	  cp ../results/i686-pc-linux-gnu+gcc4.0/bits/$$i.output $$i/cmp/i686-pc-linux-gnu+gcc4.0 ; \
	  cp ../results/i686-pc-linux-gnu+gcc4.1/bits/$$i.output $$i/cmp/i686-pc-linux-gnu+gcc4.1 ; \
	  cp ../results/i686-pc-linux-gnu+icc7.1/bits/$$i.output $$i/cmp/i686-pc-linux-gnu+icc7.1 ; \
          cp ../results/mips-sgi-irix6.5+MIPSpro7.4/bits/$$i.output $$i/cmp/mips-sgi-irix6.5+MIPSpro7.4 ; \
          cp ../results/x86_64-unknown-linux-gnu+gcc3.3/bits/$$i.output $$i/cmp/x86_64-unknown-linux-gnu+gcc3.3 ; \
          cd $$i/cmp ; \
            for j in [imx]* ; do \
		if diff -q $$j generic ; then rm $$j ; fi ; done ; \
          cd ../.. ; \
	done

