SET(TRACK "Experimental")

SET(CMAKE_BUILD_TYPE Release)
SET(DEAL_II_COMPILE_EXAMPLES FALSE)
SET(TEST_PICKUP_REGEX "^performance")

SET(ENABLE_PERFORMANCE_TESTS TRUE)
IF(NOT DEFINED SKIP_SUBMISSION)
  SET(SKIP_SUBMISSION TRUE)
ENDIF()

INCLUDE(${CMAKE_CURRENT_LIST_DIR}/run_testsuite.cmake)
