############################################################
# $Id$
# Copyright (C) 2000, 2001, 2002, 2003, 2005, 2006, 2007, 2008, 2009, 2010 by the deal.II authors
############################################################

include ../Makefile.paths
include $D/common/Make.global_options

# we have a couple tests in this directory that take about 10
# minutes. set the limit to 30
ULIMIT_LIMIT=1800

include ../Makefile.rules
include Makefile.depend
include Makefile.tests
