############################################################
# $Id$
# Copyright (C) 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2010 by the deal.II authors
############################################################

include ../Makefile.paths
include $D/common/Make.global_options
include ../Makefile.rules
include Makefile.depend
include Makefile.tests
