#!/bin/bash
## ---------------------------------------------------------------------
##
## Copyright (C) 2018 by the deal.II authors
##
## This file is part of the deal.II library.
##
## The deal.II library is free software; you can use it, redistribute
## it, and/or modify it under the terms of the GNU Lesser General
## Public License as published by the Free Software Foundation; either
## version 2.1 of the License, or (at your option) any later version.
## The full text of the license can be found in the file LICENSE at
## the top level of the deal.II distribution.
##
## ---------------------------------------------------------------------

#
# This script does the same thing as contrib/utilities/indent but only
# reformats files which have changed (or have been added but neither
# staged/commited) since the last merge commit to the master branch. It
# should be run as
#
#    make indent-branch
#
# from a build directory.
#

if [ ! -f contrib/utilities/indent_common.sh ]; then
  echo "*** This script must be run from the top-level directory of deal.II."
  exit 1
fi

source contrib/utilities/indent_common.sh

#
# Run sanity checks:
#

checks

#
# Process all source and header files:
#

process_changed "tests include source examples" ".*\.(cc|h|cu|cuh)" format_file
process_changed "source" ".*\.inst.in" format_inst

#
# Fix permissions and convert to unix line ending if necessary:
#

process_changed "tests include source examples" \
  ".*\.(cc|h|cu|cuh|inst.in|output.*|cmake)" fix_permissions

process_changed "tests include source examples" \
  ".*\.(cc|h|cu|cuh|inst.in|cmake)" dos_to_unix
