#!/bin/bash
## ---------------------------------------------------------------------
##
## Copyright (C) 2018 - 2020 by the deal.II authors
##
## This file is part of the deal.II library.
##
## The deal.II library is free software; you can use it, redistribute
## it, and/or modify it under the terms of the GNU Lesser General
## Public License as published by the Free Software Foundation; either
## version 2.1 of the License, or (at your option) any later version.
## The full text of the license can be found in the file LICENSE at
## the top level of the deal.II distribution.
##
## ---------------------------------------------------------------------

#
# This script does the same thing as contrib/utilities/indent-all but only
# reformats files which have changed (or have been added but neither
# staged/committed) since the last merge commit to the master branch.
#
# The script needs to be executed as
#   ./contrib/utilities/indent
# from the top-level directory of the source tree, or via
#   make indent
# from a build directory.
#
# The script can be invoked with DEAL_II_CLANG_FORMAT to change
# the default version of clang-format. For example:
#   DEAL_II_CLANG_FORMAT=clang-format-6.0 ./contrib/utilities/indent
# or,
#   make DEAL_II_CLANG_FORMAT="clang-format-6.0" indent
#
# Note: If the script is invoked with REPORT_ONLY=true set,
#   REPORT_ONLY=true ./contrib/utilities/indent
# or,
#   make REPORT_ONLY=true indent
# then indentation errors will only be reported without any actual file
# changes.
#

if [ ! -f contrib/utilities/indent_common.sh ]; then
  echo "*** This script must be run from the top-level directory of deal.II."
  exit 1
fi

source contrib/utilities/indent_common.sh

#
# Run sanity checks:
#

checks

#
# Process all source and header files:
#

process_changed "tests include source examples cmake/scripts contrib/python-bindings" ".*\.(cc|h|cu|cuh)" format_file
process_changed "source" ".*\.inst.in" format_inst

#
# Fix permissions and convert to unix line ending if necessary:
#

process_changed "tests include source examples cmake/scripts contrib/python-bindings" \
  ".*\.(cc|h|cu|cuh|inst.in|output.*|cmake)" fix_permissions

process_changed "tests include source examples cmake/scripts contrib/python-bindings" \
  ".*\.(cc|h|cu|cuh|inst.in|cmake)" dos_to_unix

#
# Removing trailing whitespace
#

process_changed "tests include source examples cmake/scripts contrib/python-bindings doc" \
  ".*\.(cc|h|cu|cuh|html|dox|txt)" remove_trailing_whitespace


#
# Ensure only a single newline at end of files
#
ensure_single_trailing_newline()
{
  f=$1

  # Remove newlines at end of file
  # Check that the current line only contains newlines
  # If it doesn't match, print it
  # If it does match and we're not at the end of the file,
  # append the next line to the current line and repeat the check
  # If it does match and we're at the end of the file,
  # remove the line.
  sed -e :a -e '/^\n*$/{$d;N;};/\n$/ba' $f >$f.tmpi

  # Then add a newline to the end of the file
  # '$' denotes the end of file
  # 'a\' appends the following text (which in this case is nothing)
  # on a new line
  sed -e '$a\' $f.tmpi >$f.tmp

  diff -q $f $f.tmp >/dev/null || mv $f.tmp $f
  rm -f $f.tmp $f.tmpi
}
export -f ensure_single_trailing_newline

process_changed "tests include source examples cmake/scripts contrib/python-bindings doc" \
  ".*\.(cc|h|cu|cuh|html|dox|txt)" ensure_single_trailing_newline

