#
# Set up deal.II specific definitions
#


SET(DEAL_II_PACKAGE_NAME "deal.II")

SET(DEAL_II_PACKAGE_VERSION ${VERSION})

SET(DEAL_II_PACKAGE_STRING
  "${DEAL_II_PACKAGE_NAME} ${DEAL_II_PACKAGE_VERSION}"
  )

STRING(REGEX REPLACE
  "^([0-9]+)\\..*" "\\1" DEAL_II_MAJOR "${VERSION}"
  )
STRING(REGEX REPLACE
  "^[0-9]+\\.([0-9]+).*" "\\1" DEAL_II_MINOR "${VERSION}"
  )

SET(DEAL_II_PATH ${CMAKE_INSTALL_PREFIX})

SET(DEAL_II_PACKAGE_BUGREPORT "dealii@dealii.org")

SET(DEAL_II_PACKAGE_TARNAME ${DEAL_II_PACKAGE_NAME}) #TODO

SET(DEAL_II_PACKAGE_URL "http://www.dealii.org")

