#
# Try to find the UMFPACK library
#

INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(UMFPACK_INCLUDE_DIR umfpack.h
  HINTS
    ${UMFPACK_DIR}/include
    $ENV{UMFPACK_DIR}/include
  PATH_SUFFIXES umfpack
)

FIND_LIBRARY(UMFPACK_LIBRARY
  NAMES umfpack
  HINTS
    ${UMFPACK_DIR}
    $ENV{UMFPACK_DIR}
  PATH_SUFFIXES lib${LIB_SUFFIX} lib64 lib
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(UMFPACK DEFAULT_MSG UMFPACK_LIBRARY UMFPACK_INCLUDE_DIR)

IF(UMFPACK_FOUND)
  MARK_AS_ADVANCED(
    UMFPACK_LIBRARY
    UMFPACK_INCLUDE_DIR
  )
ENDIF()

