#
# Try to find the P4EST library
#

INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(P4EST_INCLUDE_DIR p4est.h
  HINTS
    ${P4EST_DIR}/include
    $ENV{P4EST_DIR}/include
  )

FIND_LIBRARY(P4EST_LIBRARY
  NAMES p4est
  HINTS
    ${P4EST_DIR}
    $ENV{P4EST_DIR}
  PATH_SUFFIXES lib${LIB_SUFFIX} lib64 lib
  )

FIND_LIBRARY(P4EST_DEBUG_LIBRARY
  NAMES p4est_debug p4est.g
  HINTS
    ${P4EST_DIR}
    $ENV{P4EST_DIR}
  PATH_SUFFIXES lib${LIB_SUFFIX} lib64 lib
  )

FIND_PACKAGE_HANDLE_STANDARD_ARGS(P4EST DEFAULT_MSG P4EST_LIBRARY P4EST_INCLUDE_DIR)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(P4EST_DEBUG DEFAULT_MSG P4EST_DEBUG_LIBRARY P4EST_INCLUDE_DIR)

IF(P4EST_FOUND)
  MARK_AS_ADVANCED(
    P4EST_LIBRARY
    P4EST_DEBUG_LIBRARY
    P4EST_INCLUDE_DIR
  )
ENDIF()

