#
# Try to find the UMFPACK library
#

INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(UMFPACK_INCLUDE_DIR umfpack.h
)

FIND_LIBRARY(UMFPACK_LIBRARY
  NAMES umfpack
  PATH_SUFFIXES lib64 lib
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(UMFPACK DEFAULT_MSG UMFPACK_LIBRARY UMFPACK_INCLUDE_DIR)

IF(UMFPACK_FOUND)
  MARK_AS_ADVANCED(
    UMFPACK_LIBRARY
    UMFPACK_INCLUDE_DIR
  )
ENDIF()

