# Try to find AMD

INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(AMD_INCLUDE_DIR amd.h
  HINTS
  $ENV{AMD_INCLUDE_DIR}
  ${AMD_INCLUDE_DIR}
)

FIND_LIBRARY(AMD_LIBRARY
  NAMES amd
  PATHS
  $ENV{AMD_LIBRARY_DIR}
  ${AMD_LIBRARY_DIR}
  PATH_SUFFIXES lib64 lib
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(AMD DEFAULT_MSG AMD_LIBRARY AMD_INCLUDE_DIR)

IF(AMD_FOUND)
  MARK_AS_ADVANCED(
    AMD_LIBRARY
    AMD_INCLUDE_DIR
  )
ENDIF()
