# Try to find SC

INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(SC_INCLUDE_DIR sc.h)


FIND_LIBRARY(SC_LIBRARY
  NAMES sc
  PATH_SUFFIXES lib${LIB_SUFFIX} lib64 lib
)

FIND_LIBRARY(SC_DEBUG_LIBRARY
  NAMES sc_debug sc.g
  PATH_SUFFIXES lib${LIB_SUFFIX} lib64 lib
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SC DEFAULT_MSG SC_LIBRARY SC_INCLUDE_DIR)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SC_DEBUG DEFAULT_MSG SC_DEBUG_LIBRARY SC_INCLUDE_DIR)

IF(SC_FOUND)
  MARK_AS_ADVANCED(
    SC_LIBRARY
    SC_DEBUG_LIBRARY
    SC_INCLUDE_DIR
  )
ENDIF()
