# Try to find METIS

INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(METIS_INCLUDE_DIR metis/metis.h
  HINTS
  $ENV{NETCDF_INCLUDE_DIR}
  ${NETCDF_INCLUDE_DIR}
)

FIND_LIBRARY(METIS_LIBRARY
  NAMES metis
  PATHS
  $ENV{NETCDF_LIBRARY_DIR}
  ${NETCDF_LIBRARY_DIR}
  PATH_SUFFIXES lib64 lib
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(METIS DEFAULT_MSG METIS_LIBRARY METIS_INCLUDE_DIR)

IF(METIS_FOUND)
  MARK_AS_ADVANCED(
    METIS_LIBRARY
    METIS_INCLUDE_DIR
  )
ENDIF()
