# Try to find NETCDF

INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(NETCDF_INCLUDE_DIR netcdf.hh
  HINTS
  $ENV{NETCDF_INCLUDE_DIR}
  ${NETCDF_INCLUDE_DIR}
)

FIND_LIBRARY(NETCDF_LIBRARY
  NAMES libnetcdf_c++.so libnetcdf_cpp.so
  PATHS
  $ENV{NETCDF_LIBRARY_DIR}
  ${NETCDF_LIBRARY_DIR}
  PATH_SUFFIXES lib64 lib
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(NETCDF DEFAULT_MSG NETCDF_LIBRARY NETCDF_INCLUDE_DIR)

IF(NETCDF_FOUND)
  MARK_AS_ADVANCED(
    NETCDF_LIBRARY
    NETCDF_INCLUDE_DIR
  )
ENDIF()
