# Try to find AMD

INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(AMD_INCLUDE_DIR amd.h
)

FIND_LIBRARY(AMD_LIBRARY
  NAMES amd
  PATH_SUFFIXES lib64 lib
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(AMD DEFAULT_MSG AMD_LIBRARY AMD_INCLUDE_DIR)

IF(AMD_FOUND)
  MARK_AS_ADVANCED(
    AMD_LIBRARY
    AMD_INCLUDE_DIR
  )
ENDIF()
