#
# Try to find the ARPACK library
#

INCLUDE(FindPackageHandleStandardArgs)

FIND_LIBRARY(ARPACK_LIBRARY
  NAMES arpack
  PATH_SUFFIXES lib64 lib
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(ARPACK DEFAULT_MSG ARPACK_LIBRARY)

IF(ARPACK_FOUND)
  MARK_AS_ADVANCED(
    ARPACK_LIBRARY
  )
ENDIF()

