// ------------------------------------------------------------------------
//
// SPDX-License-Identifier: LGPL-2.1-or-later
// Copyright (C) 2018 - 2024 by the deal.II authors
//
// This file is part of the deal.II library.
//
// Part of the source code is dual licensed under Apache-2.0 WITH
// LLVM-exception OR LGPL-2.1-or-later. Detailed license information
// governing the source code and code contributions can be found in
// LICENSE.md and CONTRIBUTING.md at the top level directory of deal.II.
//
// ------------------------------------------------------------------------


#ifndef dealii_gmsh_parameters_h
#define dealii_gmsh_parameters_h

#include <deal.II/base/config.h>

#ifdef DEAL_II_WITH_GMSH

#  ifdef DEAL_II_WITH_OPENCASCADE
#    include <TopoDS_CompSolid.hxx>
#    include <TopoDS_Compound.hxx>
#    include <TopoDS_Edge.hxx>
#    include <TopoDS_Face.hxx>
#    include <TopoDS_Shape.hxx>
#    include <TopoDS_Vertex.hxx>
#  endif

#  include <deal.II/grid/tria.h>


#  ifdef DEAL_II_GMSH_WITH_API
#    include <deal.II/base/mpi.h>

#    include <deal.II/distributed/fully_distributed_tria.h>

#    include <gmsh.h>
#  endif


DEAL_II_NAMESPACE_OPEN

#  ifndef DOXYGEN
class ParameterHandler;
#  endif

/**
 * A collection of %Gmsh related utilities and classes.
 */
namespace Gmsh
{
  /**
   * A parameter class used to pass options to the %Gmsh executable.
   */
  class AdditionalParameters
  {
  public:
    /**
     * Set all additional parameters to their default values.
     */
    AdditionalParameters(const double       characteristic_length = 1.0,
                         const std::string &output_base_name      = "");

    /**
     * Call prm.add_parameter for each member of the AdditionalParameters class.
     */
    void
    add_parameters(ParameterHandler &prm);

    /**
     * The characteristic length used for the definition of the %Gmsh grid.
     *
     * %Gmsh will try to make sure that the size of each edge is as close as
     * possible to this value.
     */
    double characteristic_length = 1.0;

    /**
     * Base name for the output files. The base name may contain a directory
     * (followed by a slash), and must contain the base of the names of files
     * to be created.
     *
     * If this variable is left empty, then a temporary directory will be used,
     * and both the files written into it as well as the temporary directory
     * will be removed when not needed any more.
     */
    std::string output_base_name = {};
  };

#  ifdef DEAL_II_WITH_OPENCASCADE
  /**
   * Given a smooth closed curve, create a triangulation from it using
   * %Gmsh.
   *
   * The input curve @p boundary should be closed.
   */
  template <int spacedim>
  void
  create_triangulation_from_boundary_curve(
    const TopoDS_Edge          &boundary,
    Triangulation<2, spacedim> &tria,
    const AdditionalParameters &prm = AdditionalParameters());
#  endif

#  ifdef DEAL_II_GMSH_WITH_API
  /**
   * Read a partitioned GMSH mesh file and create a fully distributed
   * triangulation in deal.II.
   *
   * This function reads partitioned mesh files generated by GMSH's internal
   * partitioner (usually metis) and constructs a fully distributed
   * triangulation that can be used in parallel computations with MPI. The
   * function automatically handles ghost cell identification, vertex
   * coordinates, and cell connectivity across processor boundaries.
   *
   * In order to generate a set of partitioned mesh files that can be used with
   * this function, you could use the `GMSH` command line tool with the
   * following options:
   * @code
   * gmsh -part 4 -part_ghosts -part_split -save {input_file}
   * @endcode
   *
   * This will generate a set of mesh files named like `{input_file}_1.msh`,
   * `{input_file}_2.msh`, etc.
   *
   * In the command above, {input_file} can be any valid GMSH mesh input file.
   *
   * The mesh files are expected to follow the naming convention:
   * - For single processor: `{file_prefix}.{file_suffix}`
   * - For multiple processors: `{file_prefix}_{rank+1}.{file_suffix}` where
   *   rank goes from 1 to number of processors
   *
   * @tparam dim       The dimension of the triangulation (1, 2, or 3).
   * @tparam spacedim  The spatial dimension in which the triangulation lives.
   *
   * @param[out] tria         The distributed triangulation to be populated.
   * @param[in]  mpi_comm     The MPI communicator.
   * @param[in]  file_prefix  Prefix of mesh files.
   * @param[in]  file_suffix  Suffix of mesh files.
   *
   * @pre  Triangulation must be empty.
   * @pre  Mesh files must match the number of MPI ranks. An exception is thrown
   * if there are more (or less) files than ranks.
   *
   * @note Mesh file is partitioned by Gmsh api using command
   * @note The function uses GMSH's API to read the mesh and requires GMSH to be
   * initialized before calling this function.
   */
  template <int dim, int spacedim>
  void
  read_partitioned_msh(
    parallel::fullydistributed::Triangulation<dim, spacedim> &tria,
    const MPI_Comm                                            mpi_comm,
    const std::string &file_prefix = "mesh",
    const std::string &file_suffix = "msh");
#  endif // DEAL_II_GMSH_WITH_API

} // namespace Gmsh

DEAL_II_NAMESPACE_CLOSE

#else

// Make sure the scripts that create the C++20 module input files have
// something to latch on if the preprocessor #ifdef above would
// otherwise lead to an empty content of the file.
DEAL_II_NAMESPACE_OPEN
DEAL_II_NAMESPACE_CLOSE

#endif
#endif
