../../lib/libbasic.a(fe.o): fe.cc ../../include/fe/fe.h ../../include/../deal/dfmatrix.h \
 /usr/include/stdio.h /usr/include/sys/feature_tests.h \
 /usr/include/sys/va_list.h ../../include/../deal/dvector.h \
 ../../include/../deal/types.h /usr/include/stdlib.h \
 ../../include/../deal/errors.h ../../include/../deal/vectorbase.h \
 ../../include/../deal/ivector.h ../../include/grid/point.h \
 ../../include/basic/exceptions.h /usr/local/include/g++/iostream.h \
 /usr/local/include/g++/streambuf.h /usr/local/include/g++/libio.h \
 /usr/local/lib/g++-include/_G_config.h ../../include/grid/tria.h \
 /usr/local/include/g++/vector.h /usr/local/include/g++/algobase.h \
 /usr/local/include/g++/pair.h /usr/local/include/g++/stl_config.h \
 /usr/local/include/g++/stl_relops.h /usr/local/include/g++/stl_pair.h \
 /usr/local/include/g++/iterator.h /usr/local/include/g++/function.h \
 /usr/local/lib/gcc-lib/sparc-sun-solaris2.5.1/2.8.0/include/stddef.h \
 /usr/local/include/g++/stl_function.h \
 /usr/local/include/g++/stl_iterator.h \
 /usr/local/include/g++/type_traits.h \
 /usr/local/include/g++/stl_construct.h \
 /usr/local/lib/g++-include/new.h /usr/local/lib/g++-include/std/new.h \
 /usr/local/lib/g++-include/std/cstddef.h \
 /usr/local/include/g++/stl_raw_storage_iter.h \
 /usr/local/include/g++/stl_algobase.h /usr/include/string.h \
 /usr/local/lib/gcc-lib/sparc-sun-solaris2.5.1/2.8.0/include/limits.h \
 /usr/local/lib/gcc-lib/sparc-sun-solaris2.5.1/2.8.0/include/syslimits.h \
 /usr/include/limits.h /usr/include/sys/isa_defs.h \
 /usr/local/include/g++/stl_uninitialized.h \
 /usr/local/include/g++/alloc.h /usr/local/include/g++/stl_alloc.h \
 /usr/local/sparc-sun-solaris2.5.1/include/assert.h \
 /usr/local/include/g++/stl_vector.h ../../include/grid/tria_line.h \
 ../../include/grid/tria_quad.h ../../include/grid/tria_boundary.h \
 ../../include/fe/quadrature.h
../../lib/libbasic.a(fe_lib.o): fe_lib.cc ../../include/fe/fe_lib.h ../../include/fe/fe.h \
 ../../include/../deal/dfmatrix.h /usr/include/stdio.h \
 /usr/include/sys/feature_tests.h /usr/include/sys/va_list.h \
 ../../include/../deal/dvector.h ../../include/../deal/types.h \
 /usr/include/stdlib.h ../../include/../deal/errors.h \
 ../../include/../deal/vectorbase.h ../../include/../deal/ivector.h \
 ../../include/grid/point.h ../../include/basic/exceptions.h \
 /usr/local/include/g++/iostream.h /usr/local/include/g++/streambuf.h \
 /usr/local/include/g++/libio.h /usr/local/lib/g++-include/_G_config.h \
 ../../include/grid/tria.h /usr/local/include/g++/vector.h \
 /usr/local/include/g++/algobase.h /usr/local/include/g++/pair.h \
 /usr/local/include/g++/stl_config.h \
 /usr/local/include/g++/stl_relops.h /usr/local/include/g++/stl_pair.h \
 /usr/local/include/g++/iterator.h /usr/local/include/g++/function.h \
 /usr/local/lib/gcc-lib/sparc-sun-solaris2.5.1/2.8.0/include/stddef.h \
 /usr/local/include/g++/stl_function.h \
 /usr/local/include/g++/stl_iterator.h \
 /usr/local/include/g++/type_traits.h \
 /usr/local/include/g++/stl_construct.h \
 /usr/local/lib/g++-include/new.h /usr/local/lib/g++-include/std/new.h \
 /usr/local/lib/g++-include/std/cstddef.h \
 /usr/local/include/g++/stl_raw_storage_iter.h \
 /usr/local/include/g++/stl_algobase.h /usr/include/string.h \
 /usr/local/lib/gcc-lib/sparc-sun-solaris2.5.1/2.8.0/include/limits.h \
 /usr/local/lib/gcc-lib/sparc-sun-solaris2.5.1/2.8.0/include/syslimits.h \
 /usr/include/limits.h /usr/include/sys/isa_defs.h \
 /usr/local/include/g++/stl_uninitialized.h \
 /usr/local/include/g++/alloc.h /usr/local/include/g++/stl_alloc.h \
 /usr/local/sparc-sun-solaris2.5.1/include/assert.h \
 /usr/local/include/g++/stl_vector.h ../../include/grid/tria_line.h \
 ../../include/grid/tria_quad.h ../../include/grid/tria_boundary.h
../../lib/libbasic.a(quadrature_lib.o): quadrature_lib.cc ../../include/fe/quadrature_lib.h \
 ../../include/fe/quadrature.h ../../include/grid/point.h \
 ../../include/basic/exceptions.h /usr/local/include/g++/iostream.h \
 /usr/local/include/g++/streambuf.h /usr/local/include/g++/libio.h \
 /usr/local/lib/g++-include/_G_config.h \
 /usr/local/include/g++/vector.h /usr/local/include/g++/algobase.h \
 /usr/local/include/g++/pair.h /usr/local/include/g++/stl_config.h \
 /usr/local/include/g++/stl_relops.h /usr/local/include/g++/stl_pair.h \
 /usr/local/include/g++/iterator.h /usr/local/include/g++/function.h \
 /usr/local/lib/gcc-lib/sparc-sun-solaris2.5.1/2.8.0/include/stddef.h \
 /usr/local/include/g++/stl_function.h \
 /usr/local/include/g++/stl_iterator.h \
 /usr/local/include/g++/type_traits.h \
 /usr/local/include/g++/stl_construct.h \
 /usr/local/lib/g++-include/new.h /usr/local/lib/g++-include/std/new.h \
 /usr/local/lib/g++-include/std/cstddef.h \
 /usr/local/include/g++/stl_raw_storage_iter.h \
 /usr/local/include/g++/stl_algobase.h /usr/include/string.h \
 /usr/include/sys/feature_tests.h \
 /usr/local/lib/gcc-lib/sparc-sun-solaris2.5.1/2.8.0/include/limits.h \
 /usr/local/lib/gcc-lib/sparc-sun-solaris2.5.1/2.8.0/include/syslimits.h \
 /usr/include/limits.h /usr/include/sys/isa_defs.h \
 /usr/include/stdlib.h /usr/local/include/g++/stl_uninitialized.h \
 /usr/local/include/g++/alloc.h /usr/local/include/g++/stl_alloc.h \
 /usr/local/sparc-sun-solaris2.5.1/include/assert.h \
 /usr/local/include/g++/stl_vector.h
../../lib/libbasic.g.a(fe.go): fe.cc ../../include/fe/fe.h ../../include/../deal/dfmatrix.h \
 /usr/include/stdio.h /usr/include/sys/feature_tests.h \
 /usr/include/sys/va_list.h ../../include/../deal/dvector.h \
 ../../include/../deal/types.h /usr/include/stdlib.h \
 ../../include/../deal/errors.h ../../include/../deal/vectorbase.h \
 ../../include/../deal/ivector.h ../../include/grid/point.h \
 ../../include/basic/exceptions.h /usr/local/include/g++/iostream.h \
 /usr/local/include/g++/streambuf.h /usr/local/include/g++/libio.h \
 /usr/local/lib/g++-include/_G_config.h ../../include/grid/tria.h \
 /usr/local/include/g++/vector.h /usr/local/include/g++/algobase.h \
 /usr/local/include/g++/pair.h /usr/local/include/g++/stl_config.h \
 /usr/local/include/g++/stl_relops.h /usr/local/include/g++/stl_pair.h \
 /usr/local/include/g++/iterator.h /usr/local/include/g++/function.h \
 /usr/local/lib/gcc-lib/sparc-sun-solaris2.5.1/2.8.0/include/stddef.h \
 /usr/local/include/g++/stl_function.h \
 /usr/local/include/g++/stl_iterator.h \
 /usr/local/include/g++/type_traits.h \
 /usr/local/include/g++/stl_construct.h \
 /usr/local/lib/g++-include/new.h /usr/local/lib/g++-include/std/new.h \
 /usr/local/lib/g++-include/std/cstddef.h \
 /usr/local/include/g++/stl_raw_storage_iter.h \
 /usr/local/include/g++/stl_algobase.h /usr/include/string.h \
 /usr/local/lib/gcc-lib/sparc-sun-solaris2.5.1/2.8.0/include/limits.h \
 /usr/local/lib/gcc-lib/sparc-sun-solaris2.5.1/2.8.0/include/syslimits.h \
 /usr/include/limits.h /usr/include/sys/isa_defs.h \
 /usr/local/include/g++/stl_uninitialized.h \
 /usr/local/include/g++/alloc.h /usr/local/include/g++/stl_alloc.h \
 /usr/local/sparc-sun-solaris2.5.1/include/assert.h \
 /usr/local/include/g++/stl_vector.h ../../include/grid/tria_line.h \
 ../../include/grid/tria_quad.h ../../include/grid/tria_boundary.h \
 ../../include/fe/quadrature.h
../../lib/libbasic.g.a(fe_lib.go): fe_lib.cc ../../include/fe/fe_lib.h ../../include/fe/fe.h \
 ../../include/../deal/dfmatrix.h /usr/include/stdio.h \
 /usr/include/sys/feature_tests.h /usr/include/sys/va_list.h \
 ../../include/../deal/dvector.h ../../include/../deal/types.h \
 /usr/include/stdlib.h ../../include/../deal/errors.h \
 ../../include/../deal/vectorbase.h ../../include/../deal/ivector.h \
 ../../include/grid/point.h ../../include/basic/exceptions.h \
 /usr/local/include/g++/iostream.h /usr/local/include/g++/streambuf.h \
 /usr/local/include/g++/libio.h /usr/local/lib/g++-include/_G_config.h \
 ../../include/grid/tria.h /usr/local/include/g++/vector.h \
 /usr/local/include/g++/algobase.h /usr/local/include/g++/pair.h \
 /usr/local/include/g++/stl_config.h \
 /usr/local/include/g++/stl_relops.h /usr/local/include/g++/stl_pair.h \
 /usr/local/include/g++/iterator.h /usr/local/include/g++/function.h \
 /usr/local/lib/gcc-lib/sparc-sun-solaris2.5.1/2.8.0/include/stddef.h \
 /usr/local/include/g++/stl_function.h \
 /usr/local/include/g++/stl_iterator.h \
 /usr/local/include/g++/type_traits.h \
 /usr/local/include/g++/stl_construct.h \
 /usr/local/lib/g++-include/new.h /usr/local/lib/g++-include/std/new.h \
 /usr/local/lib/g++-include/std/cstddef.h \
 /usr/local/include/g++/stl_raw_storage_iter.h \
 /usr/local/include/g++/stl_algobase.h /usr/include/string.h \
 /usr/local/lib/gcc-lib/sparc-sun-solaris2.5.1/2.8.0/include/limits.h \
 /usr/local/lib/gcc-lib/sparc-sun-solaris2.5.1/2.8.0/include/syslimits.h \
 /usr/include/limits.h /usr/include/sys/isa_defs.h \
 /usr/local/include/g++/stl_uninitialized.h \
 /usr/local/include/g++/alloc.h /usr/local/include/g++/stl_alloc.h \
 /usr/local/sparc-sun-solaris2.5.1/include/assert.h \
 /usr/local/include/g++/stl_vector.h ../../include/grid/tria_line.h \
 ../../include/grid/tria_quad.h ../../include/grid/tria_boundary.h
../../lib/libbasic.g.a(quadrature_lib.go): quadrature_lib.cc ../../include/fe/quadrature_lib.h \
 ../../include/fe/quadrature.h ../../include/grid/point.h \
 ../../include/basic/exceptions.h /usr/local/include/g++/iostream.h \
 /usr/local/include/g++/streambuf.h /usr/local/include/g++/libio.h \
 /usr/local/lib/g++-include/_G_config.h \
 /usr/local/include/g++/vector.h /usr/local/include/g++/algobase.h \
 /usr/local/include/g++/pair.h /usr/local/include/g++/stl_config.h \
 /usr/local/include/g++/stl_relops.h /usr/local/include/g++/stl_pair.h \
 /usr/local/include/g++/iterator.h /usr/local/include/g++/function.h \
 /usr/local/lib/gcc-lib/sparc-sun-solaris2.5.1/2.8.0/include/stddef.h \
 /usr/local/include/g++/stl_function.h \
 /usr/local/include/g++/stl_iterator.h \
 /usr/local/include/g++/type_traits.h \
 /usr/local/include/g++/stl_construct.h \
 /usr/local/lib/g++-include/new.h /usr/local/lib/g++-include/std/new.h \
 /usr/local/lib/g++-include/std/cstddef.h \
 /usr/local/include/g++/stl_raw_storage_iter.h \
 /usr/local/include/g++/stl_algobase.h /usr/include/string.h \
 /usr/include/sys/feature_tests.h \
 /usr/local/lib/gcc-lib/sparc-sun-solaris2.5.1/2.8.0/include/limits.h \
 /usr/local/lib/gcc-lib/sparc-sun-solaris2.5.1/2.8.0/include/syslimits.h \
 /usr/include/limits.h /usr/include/sys/isa_defs.h \
 /usr/include/stdlib.h /usr/local/include/g++/stl_uninitialized.h \
 /usr/local/include/g++/alloc.h /usr/local/include/g++/stl_alloc.h \
 /usr/local/sparc-sun-solaris2.5.1/include/assert.h \
 /usr/local/include/g++/stl_vector.h
