#!/bin/bash
## ------------------------------------------------------------------------
##
## SPDX-License-Identifier: LGPL-2.1-or-later
## Copyright (C) 2018 by the deal.II authors
##
## This file is part of the deal.II library.
##
## Part of the source code is dual licensed under Apache-2.0 WITH
## LLVM-exception OR LGPL-2.1-or-later. Detailed license information
## governing the source code and code contributions can be found in
## LICENSE.md and CONTRIBUTING.md at the top level directory of deal.II.
##
## ------------------------------------------------------------------------

#
# This pre-commit hook checks formatting for each commit.
#

BASEDIR="$(git rev-parse --show-toplevel 2>/dev/null)"

if [ ! -f "${BASEDIR}"/contrib/utilities/indent ]; then
  echo "*** This script must be run from within the deal.II git repository."
  exit 1
fi

cd "${BASEDIR}"
OUTPUT="$(REPORT_ONLY=true "${BASEDIR}"/contrib/utilities/indent)"

if [ ! -z "${OUTPUT}" ]; then
  echo "git commit aborted due to formatting issues:"
  echo "${OUTPUT}"
  echo ""
  echo "Please run ./contrib/utilities/indent to fix these issues and try again."
  exit 1
fi
