#!/bin/bash
## ---------------------------------------------------------------------
##
## Copyright (C) 2018 by the deal.II authors
##
## This file is part of the deal.II library.
##
## The deal.II library is free software; you can use it, redistribute
## it, and/or modify it under the terms of the GNU Lesser General
## Public License as published by the Free Software Foundation; either
## version 2.1 of the License, or (at your option) any later version.
## The full text of the license can be found in the file LICENSE at
## the top level of the deal.II distribution.
##
## ---------------------------------------------------------------------

#
# This pre-commit hook checks formatting for each commit.
#

BASEDIR="$(git rev-parse --show-toplevel 2>/dev/null)"

if [ ! -f "${BASEDIR}"/contrib/utilities/indent-branch ]; then
  echo "*** This script must be run from within the deal.II git repository."
  exit 1
fi

cd "${BASEDIR}"
OUTPUT="$(REPORT_ONLY=true "${BASEDIR}"/contrib/utilities/indent-branch)"

if [ ! -z "${OUTPUT}" ]; then
  echo "git commit aborted due to formatting issues:"
  echo "${OUTPUT}"
  echo ""
  echo "Please run ./contrib/utilities/indent-branch to fix these issues and try again."
  exit 1
fi
