#!/bin/sh
#
# $Id$
#
# Rerun configure with the same options as last time.

if test -f config.log
then
  perl -e 'while(<>) { if(s/^ *\$ *(.*)configure/$1configure/) { exec $_; } }' config.log
else
  echo 'No config.log found. Did you ever run configure?'
fi
