Major:

* The documentation

  - Update FAQ hyperlinks to point to googlegroups
    (WB: actually, no -- this is a change that should happen on
     mainline once we have migrated the whole wiki)

  - Write a page on how to use deal.II in external CMake projects.
    (doc/development/toc.html already links to it)
    (A more detailed copy of what is already standing in cmake.html)

  - Modify doc/porting.html


Minor:

* The following feature has to be written: TECPLOT

* Fixup the TODOs in
    source/lac/sparse_dircect.cc
    source/base/path_find.cc
    source/base/function_parser.cc
