#
# Configuration for the netcdf library:
#

OPTION(DEAL_II_WITH_NETCDF
  "Build deal.II with support for netcdf."
  OFF)


MACRO(FEATURE_NETCDF_FIND_EXTERNAL var)
  FIND_PACKAGE(NETCDF)

  IF(NETCDF_FOUND)
    SET(${var} TRUE)
  ENDIF()
ENDMACRO()


MACRO(FEATURE_NETCDF_CONFIGURE_EXTERNAL var)
  INCLUDE_DIRECTORIES(${NETCDF_INCLUDE_DIR})
  LIST(APPEND DEAL_II_EXTERNAL_LIBRARIES ${NETCDF_LIBRARY})
  SET(HAVE_LIBNETCDF TRUE)

  SET(${var} TRUE)
ENDMACRO()


CONFIGURE_FEATURE(NETCDF)

