#
# Configuration for the ARPACK library:
#

OPTION(DEAL_II_WITH_ARPACK
  "Build deal.II with support for doxygen and dot."
  OFF)


SET(FEATURE_ARPACK_DEPENDS
  # Currently, with enabled arpack support, we also need to setup
  # LAPACK support in deal.II:
  DEAL_II_WITH_LAPACK
  )

MACRO(FEATURE_ARPACK_FIND_EXTERNAL var)
  FIND_PACKAGE(ARPACK)

  IF(ARPACK_FOUND)
    SET(${var} TRUE)
  ENDIF()
ENDMACRO()


MACRO(FEATURE_ARPACK_CONFIGURE_EXTERNAL var)

  LIST(APPEND DEAL_II_EXTERNAL_LIBRARIES ${ARPACK_LIBRARIES})
  ADD_FLAGS(CMAKE_SHARED_LINKER_FLAGS "${ARPACK_LINKER_FLAGS}")

  SET(DEAL_II_USE_ARPACK TRUE)

  SET(${var} TRUE)
ENDMACRO()


CONFIGURE_FEATURE(ARPACK)

