#
# Configuration for the zlib library:
#

MACRO(FEATURE_ZLIB_FIND_EXTERNAL var)
  FIND_PACKAGE(ZLIB)

  IF(ZLIB_FOUND)
    SET(${var} TRUE)
  ENDIF()
ENDMACRO()


MACRO(FEATURE_ZLIB_CONFIGURE_EXTERNAL var)
  INCLUDE_DIRECTORIES(${ZLIB_INCLUDE_DIRS})
  LIST(APPEND DEAL_II_EXTERNAL_LIBRARIES ${ZLIB_LIBRARIES})
  SET(HAVE_LIBZ TRUE)

  SET(${var} TRUE)
ENDMACRO()


CONFIGURE_FEATURE(ZLIB)

