// ---------------------------------------------------------------------
//
// Copyright (C) 2003 - 2020 by the deal.II authors
//
// This file is part of the deal.II library.
//
// The deal.II library is free software; you can use it, redistribute
// it, and/or modify it under the terms of the GNU Lesser General
// Public License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
// The full text of the license can be found in the file LICENSE.md at
// the top level directory of deal.II.
//
// ---------------------------------------------------------------------



// check the cells generated by the CylindricalManifold for an
// axiparallel cylinder parallel to the y-axis

#include <deal.II/base/quadrature_lib.h>

#include <deal.II/dofs/dof_handler.h>

#include <deal.II/fe/fe_q.h>
#include <deal.II/fe/fe_values.h>
#include <deal.II/fe/mapping_c1.h>

#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/grid_tools.h>
#include <deal.II/grid/manifold_lib.h>
#include <deal.II/grid/tria.h>
#include <deal.II/grid/tria_accessor.h>
#include <deal.II/grid/tria_iterator.h>

#include "../tests.h"



template <int dim>
Point<dim>
rotate_to_y(const Point<dim> &p)
{
  if (dim == 2)
    return Point<dim>(-p[1], p[0]);
  else
    return Point<dim>(-p[1], p[0], p[2]);
}

void set_manifold(Triangulation<2> &triangulation)
{}

void set_manifold(Triangulation<3> &triangulation)
{
  static const CylindricalManifold<3> boundary(1);
  triangulation.set_manifold(0, boundary);
}

template <int dim>
void
check()
{
  Triangulation<dim> triangulation;
  GridGenerator::cylinder(triangulation);

  GridTools::transform((Point<dim>(*)(const Point<dim> &)) & rotate_to_y<dim>,
                       triangulation);

  set_manifold(triangulation);
  triangulation.refine_global(2);

  for (typename Triangulation<dim>::active_cell_iterator cell =
         triangulation.begin_active();
       cell != triangulation.end();
       ++cell)
    for (const unsigned int i : GeometryInfo<dim>::vertex_indices())
      deallog << cell->vertex(i) << std::endl;
}


int
main()
{
  initlog();

  check<2>();
  check<3>();
}
