# Generated automatically from Makefile.in by configure.
############################################################
# Makefile,v 1.15 2002/06/13 12:51:13 hartmann Exp
# Copyright (C) 2000, 2001, 2002, 2003 by the deal.II authors
############################################################

############################################################
# Include general settings for including DEAL libraries
############################################################

include ../Makefile.paths
include $D/common/Make.global_options
debug-mode = on

libraries = $(lib-deal2-1d.g) \
            $(lib-deal2-2d.g) \
            $(lib-deal2-3d.g) \
            $(lib-lac.g)  \
            $(lib-base.g)

default: run-tests

############################################################

anna_1.exe              : anna_1.g.$(OBJEXT)              $(libraries)
anna_2.exe              : anna_2.g.$(OBJEXT)              $(libraries)
anna_3.exe              : anna_3.g.$(OBJEXT)              $(libraries)
anna_4.exe              : anna_4.g.$(OBJEXT)              $(libraries)
anna_5.exe              : anna_5.g.$(OBJEXT)              $(libraries)
anna_6.exe              : anna_6.g.$(OBJEXT)              $(libraries)
data_out_01.exe         : data_out_01.g.$(OBJEXT)         $(libraries)
data_out_faces_01.exe   : data_out_faces_01.g.$(OBJEXT)   $(libraries)
dof_tools_01a.exe       : dof_tools_01a.g.$(OBJEXT)       $(libraries)
dof_tools_01b.exe       : dof_tools_01b.g.$(OBJEXT)       $(libraries)
dof_tools_01c.exe       : dof_tools_01c.g.$(OBJEXT)       $(libraries)
dof_tools_01d.exe       : dof_tools_01d.g.$(OBJEXT)       $(libraries)
dof_tools_02a.exe       : dof_tools_02a.g.$(OBJEXT)       $(libraries)
dof_tools_02b.exe       : dof_tools_02b.g.$(OBJEXT)       $(libraries)
dof_tools_02c.exe       : dof_tools_02c.g.$(OBJEXT)       $(libraries)
dof_tools_02d.exe       : dof_tools_02d.g.$(OBJEXT)       $(libraries)
dof_tools_03.exe        : dof_tools_03.g.$(OBJEXT)        $(libraries)
dof_tools_04.exe        : dof_tools_04.g.$(OBJEXT)        $(libraries)
dof_tools_05.exe        : dof_tools_05.g.$(OBJEXT)        $(libraries)
dof_tools_06.exe        : dof_tools_06.g.$(OBJEXT)        $(libraries)
dof_tools_07.exe        : dof_tools_07.g.$(OBJEXT)        $(libraries)
dof_tools_08.exe        : dof_tools_08.g.$(OBJEXT)        $(libraries)
dof_tools_09.exe        : dof_tools_09.g.$(OBJEXT)        $(libraries)
dof_tools_10.exe        : dof_tools_10.g.$(OBJEXT)        $(libraries)
dof_tools_11.exe        : dof_tools_11.g.$(OBJEXT)        $(libraries)
dof_tools_12.exe        : dof_tools_12.g.$(OBJEXT)        $(libraries)
dof_tools_13.exe        : dof_tools_13.g.$(OBJEXT)        $(libraries)
dof_tools_14.exe        : dof_tools_14.g.$(OBJEXT)        $(libraries)
dof_tools_15a.exe       : dof_tools_15a.g.$(OBJEXT)       $(libraries)
dof_tools_15b.exe       : dof_tools_15b.g.$(OBJEXT)       $(libraries)
dof_tools_15c.exe       : dof_tools_15c.g.$(OBJEXT)       $(libraries)
dof_tools_15d.exe       : dof_tools_15d.g.$(OBJEXT)       $(libraries)
dof_tools_16a.exe       : dof_tools_16a.g.$(OBJEXT)       $(libraries)
dof_tools_16b.exe       : dof_tools_16b.g.$(OBJEXT)       $(libraries)
dof_tools_16c.exe       : dof_tools_16c.g.$(OBJEXT)       $(libraries)
dof_tools_16d.exe       : dof_tools_16d.g.$(OBJEXT)       $(libraries)
dof_tools_17a.exe       : dof_tools_17a.g.$(OBJEXT)       $(libraries)
dof_tools_17b.exe       : dof_tools_17b.g.$(OBJEXT)       $(libraries)
dof_tools_17c.exe       : dof_tools_17c.g.$(OBJEXT)       $(libraries)
dof_tools_17d.exe       : dof_tools_17d.g.$(OBJEXT)       $(libraries)
dof_tools_18a.exe       : dof_tools_18a.g.$(OBJEXT)       $(libraries)
dof_tools_18b.exe       : dof_tools_18b.g.$(OBJEXT)       $(libraries)
dof_tools_18c.exe       : dof_tools_18c.g.$(OBJEXT)       $(libraries)
dof_tools_18d.exe       : dof_tools_18d.g.$(OBJEXT)       $(libraries)
fe_tools_01a.exe        : fe_tools_01a.g.$(OBJEXT)        $(libraries)
fe_tools_01b.exe        : fe_tools_01b.g.$(OBJEXT)        $(libraries)
fe_tools_01c.exe        : fe_tools_01c.g.$(OBJEXT)        $(libraries)
fe_tools_02.exe         : fe_tools_02.g.$(OBJEXT)         $(libraries)
fe_tools_03.exe         : fe_tools_03.g.$(OBJEXT)         $(libraries)
fe_tools_04.exe         : fe_tools_04.g.$(OBJEXT)         $(libraries)
fe_tools_05.exe         : fe_tools_05.g.$(OBJEXT)         $(libraries)
fe_tools_06.exe         : fe_tools_06.g.$(OBJEXT)         $(libraries)
fe_tools_07.exe         : fe_tools_07.g.$(OBJEXT)         $(libraries)
fe_tools_08.exe         : fe_tools_08.g.$(OBJEXT)         $(libraries)
gerold_1.exe            : gerold_1.g.$(OBJEXT)            $(libraries)
roy_1.exe               : roy_1.g.$(OBJEXT)               $(libraries)
denis_1.exe             : denis_1.g.$(OBJEXT)             $(libraries)
unit_support_points.exe : unit_support_points.g.$(OBJEXT) $(libraries)
parameter_handler_1.exe : parameter_handler_1.g.$(OBJEXT) $(libraries)

tests = anna_1 anna_2 anna_3 anna_4 anna_5 anna_6 \
	data_out_01 data_out_faces_01 \
        dof_tools_01a dof_tools_01b dof_tools_01c dof_tools_01d \
        dof_tools_02a dof_tools_02b dof_tools_02c dof_tools_02d \
	dof_tools_03 dof_tools_04 dof_tools_05 dof_tools_06 \
        dof_tools_07 dof_tools_08 dof_tools_09 dof_tools_10 \
	dof_tools_11 dof_tools_12 dof_tools_13 dof_tools_14 \
        dof_tools_15a dof_tools_15b dof_tools_15c dof_tools_15d \
        dof_tools_16a dof_tools_16b dof_tools_16c dof_tools_16d \
        dof_tools_17a dof_tools_17b dof_tools_17c dof_tools_17d \
        dof_tools_18a dof_tools_18b dof_tools_18c dof_tools_18d \
	fe_tools_01a fe_tools_01b fe_tools_01c \
	fe_tools_02 fe_tools_03 fe_tools_04 \
	fe_tools_05 fe_tools_06 fe_tools_07 fe_tools_08 \
	roy_1 \
        denis_1 \
	unit_support_points parameter_handler_1

############################################################


include ../Makefile.rules
include Makefile.depend
