#
# Configuration for the blas library:
#

MACRO(FEATURE_BLAS_FIND_EXTERNAL var)
  FIND_PACKAGE(BLAS)

  IF(BLAS_FOUND)
    SET(${var} TRUE)
  ENDIF()
ENDMACRO()


MACRO(FEATURE_BLAS_CONFIGURE_EXTERNAL var)
  ADD_FLAGS(CMAKE_SHARED_LINKER_FLAGS "${BLAS_LINKER_FLAGS}")

  LIST(APPEND DEAL_II_EXTERNAL_LIBRARIES
    ${BLAS_LIBRARIES}
    )

  SET(HAVE_LIBBLAS TRUE)

  SET(${var} TRUE)
ENDMACRO()


CONFIGURE_FEATURE(BLAS)

