FIND_PACKAGE(NETCDF)

IF(NOT NETCDF_FOUND)
  macro_message_not_found("netcdf" "NETCDF")
ENDIF()

INCLUDE_DIRECTORIES(${NETCDF_INCLUDE_DIR})

LIST(APPEND deal_ii_external_libraries ${NETCDF_LIBRARY})

SET(HAVE_LIBNETCDF TRUE)
