#
# Configuration for the blas library:
#

INCLUDE(CheckFunctionExists)

MACRO(FIND_FEATURE_BLAS_EXTERNAL var)

  FIND_PACKAGE(BLAS)

  IF(BLAS_FOUND)
    SET(${var} TRUE)
  ENDIF()

ENDMACRO()


MACRO(CONFIGURE_FEATURE_BLAS_EXTERNAL var)

  SET(CMAKE_SHARED_LINKER_FLAGS
    "${CMAKE_SHARED_LINKER_FLAGS} ${BLAS_LINKER_FLAGS}"
    )

  LIST(APPEND deal_ii_external_libraries
    ${BLAS_LIBRARIES}
    )

  LIST(APPEND CMAKE_REQUIRED_LIBRARIES "${BLAS_LIBRARIES}")
  LIST(APPEND CMAKE_REQUIRED_FLAGS "${BLAS_LINKER_FLAGS}")

  #
  # TODO: Reduce to the really necessary parts.
  #
  CHECK_FUNCTION_EXISTS(daxpy_ HAVE_DAXPY_)
  CHECK_FUNCTION_EXISTS(dgeevx_ HAVE_DGEEVX_)
  CHECK_FUNCTION_EXISTS(dgeev_ AVE_DGEEV_)
  CHECK_FUNCTION_EXISTS(dgelsd_ HAVE_DGELSD_)
  CHECK_FUNCTION_EXISTS(dgemm_ AVE_DGEMM_)
  CHECK_FUNCTION_EXISTS(dgemv_ AVE_DGEMV_)
  CHECK_FUNCTION_EXISTS(dgeqrf_ HAVE_DGEQRF_)
  CHECK_FUNCTION_EXISTS(dgesdd_ HAVE_DGESDD_)
  CHECK_FUNCTION_EXISTS(dgesvd_ HAVE_DGESVD_)
  CHECK_FUNCTION_EXISTS(dgetrf_ HAVE_DGETRF_)
  CHECK_FUNCTION_EXISTS(dgetri_ HAVE_DGETRI_)
  CHECK_FUNCTION_EXISTS(dgetrs_ HAVE_DGETRS_)
  CHECK_FUNCTION_EXISTS(dorgqr_ HAVE_DORGQR_)
  CHECK_FUNCTION_EXISTS(dormqr_ HAVE_DORMQR_)
  CHECK_FUNCTION_EXISTS(dstev_ AVE_DSTEV_)
  CHECK_FUNCTION_EXISTS(dsyevx_ HAVE_DSYEVX_)
  CHECK_FUNCTION_EXISTS(dsygvx_ HAVE_DSYGVX_)

  LIST(REMOVE_ITEM CMAKE_REQUIRED_LIBRARIES "${BLAS_LIBRARIES}")
  LIST(REMOVE_ITEM CMAKE_REQUIRED_FLAGS "${BLAS_LINKER_FLAGS}")

  SET(HAVE_LIBBLAS TRUE)

  SET(${var} TRUE)
ENDMACRO()


MACRO(CONFIGURE_FEATURE_BLAS_ERROR_MESSAGE)
  MESSAGE(SEND_ERROR "
Could not find the blas library!

Please ensure that the blas library is installed on your computer.
If the library is not at a default location, either provide some hints
for the autodetection, or set the relevant variables by hand in ccmake.

")
ENDMACRO()


CONFIGURE_FEATURE(BLAS)
