FIND_PACKAGE(Netcdf)

  IF(NOT DEAL_II_ALLOW_CONTRIB AND NOT TBB_FOUND)
    macro_warning_not_found("TBB")
  ENDIF()

INCLUDE_DIRECTORIES(${Netcdf_INCLUDE_DIR})

LIST(APPEND deal_ii_external_libraries ${Netcdf_LIBRARY})

SET(HAVE_LIBNETCDF TRUE)
