############################################################
# $Id: Makefile 16047 2008-05-07 16:51:50Z heltai $
# Copyright (C) 2000, 2001, 2002, 2003, 2005, 2006, 2007, 2008, 2009, 2010 by the deal.II authors
############################################################

include ../Makefile.paths
include $D/common/Make.global_options
include ../Makefile.rules
include Makefile.depend
include Makefile.tests
