SET(SUPERLU-MT_DIR "" CACHE PATH "An optional hint to a SuperLU-MT installation")
SET_IF_EMPTY(SUPERLU-MT_DIR "$ENV{SUPERLU-MT_DIR}")

DEAL_II_FIND_LIBRARY(SUPERLU-MT_LIB NAMES libsuperlu_mt_PTHREAD.a
        HINTS ${SUPERLU-MT_DIR}/lib
        PATH_PREFIXES lib${LIB_PREFIX} lib64 lib
        )

DEAL_II_FIND_PATH(SUPERLU-MT_INC slu_mt_ddefs.h
        HINTS ${SUPERLU-MT_DIR}
        PATH_SUFFIXES include
        )

DEAL_II_PACKAGE_HANDLE(SUPERLU-MT
        LIBRARIES REQUIRED SUPERLU-MT_LIB
        INCLUDE_DIRS REQUIRED SUPERLU-MT_INC
        USER_INCLUDE_DIRS REQUIRED SUPERLU-MT_INC
        CLEAR SUPERLU-MT_DIR_LIB SUPERLU-MT_INC
        )
