image:
  - Visual Studio 2019
clone_folder: c:\projects\source
build_script:
- cmd: >-
    mkdir build &&
    cd build &&
    cmake c:\projects\source -DCMAKE_BUILD_TYPE=Debug -DDEAL_II_CXX_FLAGS="-WX" -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX="c:\projects\dealii" &&
    cmake --build . --target install -- -m

for:
-
  branches:
    only:
      - master
  after_build:
    - cmd: 7z a c:\projects\source\dealii.zip c:\projects\dealii
  artifacts:
    - path: dealii.zip
      name: deal.II
