# $Id$
#
# This Makefile only recurses into the subdirs

default:
	cd step-1 ; $(MAKE)
	cd step-2 ; $(MAKE)
	cd step-3 ; $(MAKE)


run:
	cd step-1 ; $(MAKE) run
	cd step-2 ; $(MAKE) run
	cd step-3 ; $(MAKE) run

clean:
	cd step-1 ; $(MAKE) clean
	cd step-2 ; $(MAKE) clean
	cd step-3 ; $(MAKE) clean
