// ------------------------------------------------------------------------
//
// SPDX-License-Identifier: LGPL-2.1-or-later
// Copyright (C) 2015 - 2023 by the deal.II authors
//
// This file is part of the deal.II library.
//
// Part of the source code is dual licensed under Apache-2.0 WITH
// LLVM-exception OR LGPL-2.1-or-later. Detailed license information
// governing the source code and code contributions can be found in
// LICENSE.md and CONTRIBUTING.md at the top level directory of deal.II.
//
// ------------------------------------------------------------------------


// This test checks functionality of compute_active_cell_layer_within_distance
// using a mesh generated by hyper_cube with a layer_thickness of zero. The
// output is identical to that of grid_tools_halo_layer_01.cc The numerals in
// the blessed file are exact copy.


#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/grid_out.h>
#include <deal.II/grid/grid_tools.h>
#include <deal.II/grid/tria.h>

#include "../tests.h"

template <int dim>
bool
pred_mat_id(const typename Triangulation<dim>::active_cell_iterator &cell)
{
  return cell->material_id() == 2;
}

template <int dim>
void
write_mat_id_to_file(const Triangulation<dim> &tria)
{
  int                                               count = 0;
  typename Triangulation<dim>::active_cell_iterator cell  = tria.begin_active(),
                                                    endc  = tria.end();
  for (; cell != endc; ++cell, ++count)
    {
      deallog << count << ' ' << static_cast<int>(cell->material_id())
              << std::endl;
    }
  deallog << std::endl;
}


template <int dim>
void
test()
{
  deallog << "dim = " << dim << std::endl;

  Triangulation<dim> tria;
  GridGenerator::hyper_cube(tria);
  tria.refine_global(2);

  using cell_iterator = typename Triangulation<dim>::active_cell_iterator;

  // Mark a small block at the corner of the hypercube
  cell_iterator cell = tria.begin_active(), endc = tria.end();
  for (; cell != endc; ++cell)
    {
      bool mark = true;
      for (unsigned int d = 0; d < dim; ++d)
        if (cell->center()[d] > 0.5)
          {
            mark = false;
            break;
          }

      if (mark == true)
        cell->set_material_id(2);
      else
        cell->set_material_id(1);
    }

  deallog << "Grid without skin:" << std::endl;
  write_mat_id_to_file(tria);
  // Write to file to visually check result
  {
    const std::string filename =
      "grid_no_halo_" + Utilities::int_to_string(dim) + "d.vtk";
    std::ofstream f(filename);
    GridOut().write_vtk(tria, f);
  }

  std::function<bool(const cell_iterator &)> predicate = pred_mat_id<dim>;

  // Compute a halo layer around material id 2 and set it to material id 3
  const std::vector<cell_iterator> active_halo_layer =
    GridTools::compute_active_cell_layer_within_distance(
      tria, predicate, 0.); // General predicate

  AssertThrow(active_halo_layer.size() > 0, ExcMessage("No halo layer found."));
  for (typename std::vector<cell_iterator>::const_iterator it =
         active_halo_layer.begin();
       it != active_halo_layer.end();
       ++it)
    {
      (*it)->set_material_id(3);
    }

  deallog << "Grid with skin:" << std::endl;
  write_mat_id_to_file(tria);
  // Write to file to visually check result
  {
    const std::string filename =
      "grid_with_halo_" + Utilities::int_to_string(dim) + "d.vtk";
    std::ofstream f(filename);
    GridOut().write_vtk(tria, f);
  }
}


int
main()
{
  initlog();

  test<1>();
  test<2>();
  test<3>();

  return 0;
}
